"""followers

Revision ID: 83980048c546
Revises: 0bf0e576ded9
Create Date: 2020-08-10 12:43:10.174673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83980048c546'
down_revision = '0bf0e576ded9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
